# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_ENVIRONMENT: Production

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Download SQLite DB Artifact
      continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: article-aggregator-db
        path: /tmp/article_aggregator.db
    - name: Migrate database
      run: |
        dotnet run --environment $DOTNET_ENVIRONMENT --project ArticleAggregator.DbMigrations
    - name: Scrape blogs
      run: |
        dotnet run --environment $DOTNET_ENVIRONMENT --project ArticleAggregator.DataIngest 
    - name: Generate HTML
      run: |
        dotnet run --environment $DOTNET_ENVIRONMENT --project ArticleAggregator.BlogGenerator
    - name: Build CSS
      run: |
        cd ArticleAggregator.BlogGenerator/input
        npm install
        npx tailwindcss -i ./css/styles.css -o ../output/css/styles.css --minify
    - name: Copy assets
      run: |
        cp -r ./ArticleAggregator.BlogGenerator/input/images/ ./ArticleAggregator.BlogGenerator/output
        cp ./ArticleAggregator.BlogGenerator/input/favicon.ico ./ArticleAggregator.BlogGenerator/output
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: imilosk/relatively-general-dotnet
        publish_branch: main
        publish_dir: ./ArticleAggregator.BlogGenerator/output
        destination_dir: site/
    - name: Upload SQLite DB Artifact
      uses: actions/upload-artifact@v3
      with:
        name: article-aggregator-db
        path: /tmp/article_aggregator.db
