# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOTNET_ENVIRONMENT: Production

    steps:
    - name: Commit and Push changes
      run: |
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git config --global init.defaultBranch main
        git config --unset-all http.https://github.com/.extraheader
        git remote add https://github.com/imilosk/relatively-general-dotnet.git
        git checkout main
        git add .
        git commit -m "chore: Generate and commit static site HTML files"
        git push origin main
