# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOTNET_ENVIRONMENT: Production

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Migrate database
      run: dotnet run --project ArticleAggregator.DbMigrations
    - name: Generate HTML
      run: dotnet run --project ArticleAggregator.BlogGenerator
    - name: Commit and Push changes
      run: |
        cd ArticleAggregator.BlogGenerator/output
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "chore: Generate and commit static site HTML files"
        git push -u https://$GITHUB_TOKEN@github.com/imilosk/relatively-general-dotnet.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
